on: 
  #push:
  #    - main
  issue_comment:
    branches:
      - main

jobs:
  start:    
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'mekerku'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get_pull_request   
        run: sh ./.github/scripts/get_pr_as_json.sh
        env:
          pr_id: ${{ github.event.issue.number }}
          git_token: ${{ secrets.GIT_TOKEN }}
      - name: send_slack_message   
        run: sh ./.github/scripts/slack_send_message.sh
        env:
          slack_app_token: ${{ secrets.SLACK_EVILBOT_TOKEN }}
      - name: create_jira_ticket
        run: sh ./.github/scripts/create_jira_ticket.sh
        env:
          jira_user_token: ${{ secrets.JIRA_TOKEN }}