on: 
  #push:
  #    - main
  pull_request:
    branches:
      - main

jobs:
  start:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - uses: actions/checkout@v2
      - name: send_slack_message      
        run: sh ./.github/scripts/slack_send_message.sh
        env:
          slack_app_token: ${{ secrets.SLACK_EVILBOT_TOKEN }}
      - name: create_jira_ticket
        run: sh ./.github/scripts/create_jira_ticket.sh
        env:
          jira_user_token: ${{ secrets.JIRA_TOKEN }}